#nginx:
#  image: nginx
#  ports:
#    - "80:80"
drupal:
  build: docker/drupal7/
  links:
    - mysql:mysqlhost
  ports:
    - "8080"
  hostname: drupalhost
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 'mysqlRootPwd'
    MYSQL_DATABASE: 'site_dev'
    MYSQL_USER: 'site'
    MYSQL_PASSWORD: 'site'
  ports:
   - "4406:3306"
  hostname: mysqlhost