drupal:
  build: docker/drupal7/
  links:
    - mysql:mysqlhost
  expose:
    - "8080"
  hostname: drupalhost
  volumes:
    - ./src:/var/www/html
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 'mysqlRootPwd'
    MYSQL_DATABASE: 'site_dev'
    MYSQL_USER: 'site'
    MYSQL_PASSWORD: 'site'
  ports:
   - "4406:3306"
  hostname: mysqlhost
  volumes:
    - ./data:/var/lib/mysql
haproxy:
  image: tutum/haproxy
  links:
   - drupal:drupalhost
  ports:
   - "80:80"
   - "1936:1936"
  environment:
   - BACKEND_PORT=8080
   - BALANCE=roundrobin