load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }
load 'config/deploy.rb'
 
require 'capistrano/ext/multistage'
 
namespace :deploy do
 
  # Overwritten to provide flexibility for people who aren't using Rails.
  desc "Prepares one or more servers for deployment."
  task :setup, :except => { :no_release => true } do
    dirs = [deploy_to, releases_path, shared_path]
    dsites.each do |dsite|
      dirs += [shared_path + "/#{dsite}/files"]
    end
    dirs += %w(system).map { |d| File.join(shared_path, d) }
    run "umask 02 && mkdir -p #{dirs.join(' ')}" 
    
    #modify default mod for files dir
    dsites.each do |dsite|
      run "chmod 777 #{deploy_to}/#{shared_dir}/#{dsite}/files"
    end
  end
  
  desc "link file dirs" 
  task :symlinks do
    dsites.each do |dsite|
      # link settings file
      run "rm -rf #{release_path}/sites/#{dsite}/files"
      run "ln -nfs #{deploy_to}/#{shared_dir}/#{dsite}/files #{release_path}/sites/#{dsite}/files"
    end
  end
 
  # desc '[internal] Touches up the released code.'
  task :finalize_update, :except => { :no_release => true } do
    run "chmod -R g+w #{release_path}"
  end
  
  desc "Run the drush 'updatedb' task."
  task :updatedb, :roles => :db, :only => { :primary => true } do
    dsites.each do |dsite|
      run "#{drush} --uri=#{dsite} updatedb -y"
    end    
  end
 
  desc "Flush the Drupal cache system."
  task :cacheclear, :roles => :db, :only => { :primary => true } do
    dsites.each do |dsite|
      run "#{drush} --uri=#{dsite} cache-clear all"
    end    
  end
  
  desc "Run the Drupal cron jobs."
  task :runcron, :roles => :db, :only => { :primary => true } do
    dsites.each do |dsite|
      run "#{drush} --uri=#{dsite} cron"
    end    
  end
 
  namespace :web do
    desc "Set Drupal maintainance mode to online."
    task :enable do
      dsites.each do |dsite|
        run "#{drush} --uri=#{dsite} vset --always-set maintenance_mode 0"
      end
    end
 
    desc "Set Drupal maintainance mode to off-line."
    task :disable do
      dsites.each do |dsite|
        run "#{drush} --uri=#{dsite} vset --always-set maintenance_mode 1"
      end
    end
  end
 
  after "deploy", "deploy:symlinks"
  after "deploy", "deploy:web:disable"
  after "deploy", "deploy:updatedb"
  #after "deploy", "deploy:cacheclear"
  after "deploy", "deploy:cleanup"
  #after "deploy", "deploy:runcron"
  after "deploy", "deploy:web:enable"
 
  # Each of the following tasks are Rails specific. They're removed.
  task :migrate do
  end
 
  task :migrations do
  end
 
  task :cold do
  end
 
  task :start do
  end
 
  task :stop do
  end
 
  task :restart do
  end
 
end
 
 
desc "Download a backup of the database(s) from the given stage."
task :download_db, :roles => :db, :only => { :primary => true } do
  domains.each do |domain|
    filename = "#{domain}_#{stage}.sql"
    run "#{drush} --uri=#{domain} sql-dump --structure-tables-key=common > ~/#{filename}"
    download("~/#{filename}", "db/#{filename}", :via=> :scp)
  end
end